import { useRef, useState } from 'react'
import { BriefcaseBusiness, CheckCircle2, Code2, LoaderCircle, Mail, MapPin, Send, XCircle } from 'lucide-react'
import { m } from 'framer-motion'
import SectionHeading from '../components/SectionHeading'
const empty = { name: '', email: '', subject: '', message: '' }
export default function Contact({ data }) { const [form, setForm] = useState(empty), [state, setState] = useState('idle'), [notice, setNotice] = useState(''); const locked = useRef(false)
 const onChange = e => setForm({ ...form, [e.target.name]: e.target.value })
 const submit = async e => { e.preventDefault(); if (locked.current || state === 'sending') return; if (!form.name.trim() || !form.email.trim() || !form.subject.trim() || !form.message.trim()) { setState('error'); setNotice('Please complete all fields before sending.'); return }
   const endpoint = import.meta.env.VITE_GOOGLE_APPS_SCRIPT_URL
   if (!endpoint || endpoint.includes('REPLACE_WITH')) { setState('error'); setNotice('Contact endpoint is not configured yet. Add VITE_GOOGLE_APPS_SCRIPT_URL to your .env file.'); return }
   locked.current = true; setState('sending'); setNotice('')
   try { const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify({ ...form, timestamp: new Date().toISOString() }) }); if (!response.ok) throw new Error('Request failed'); setState('success'); setNotice('Message sent — thank you for reaching out.'); setForm(empty) } catch { setState('error'); setNotice('Message could not be sent. Please try again or contact me by email.') } finally { window.setTimeout(() => { locked.current = false }, 1800) }
 }
 const links = [{ Icon: Mail, label: 'Email', value: data.social.email, href: `mailto:${data.social.email}` }, { Icon: Code2, label: 'GitHub', value: 'github.com/ENGABHI', href: data.social.github }, { Icon: BriefcaseBusiness, label: 'LinkedIn', value: 'linkedin.com/in/a-dhaulakhandi', href: data.social.linkedin }, { Icon: MapPin, label: 'Location', value: data.location, href: null }]
 return <section id="contact" className="section section-pad contact-section"><SectionHeading eyebrow="08 / CONTACT" title="Let’s build something intelligent." copy="Have a conversation, collaboration, or idea in mind? I’d be glad to hear from you." />
 <div className="contact-grid"><div className="contact-info">{links.map(({ Icon, label, value, href }) => <div className="contact-link" key={label}>{Icon && <span><Icon size={18} /></span>}<div><small>{label}</small>{href ? <a href={href} target={label === 'Email' ? undefined : '_blank'} rel="noreferrer">{value}</a> : <p>{value}</p>}</div></div>)}</div>
 <m.form className="contact-form glass-panel" onSubmit={submit} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} noValidate><div className="form-row"><label>Name<input name="name" value={form.name} onChange={onChange} placeholder="Your name" required /></label><label>Email<input name="email" type="email" value={form.email} onChange={onChange} placeholder="you@example.com" required /></label></div><label>Subject<input name="subject" value={form.subject} onChange={onChange} placeholder="What would you like to discuss?" required /></label><label>Message<textarea name="message" value={form.message} onChange={onChange} placeholder="Write your message..." rows="5" required /></label>{state !== 'idle' && <p className={`form-notice ${state}`} role="status">{state === 'success' ? <CheckCircle2 /> : state === 'sending' ? <LoaderCircle className="spin" /> : <XCircle />}{notice || 'Sending your message...'}</p>}<button className="button button-primary" disabled={state === 'sending'} type="submit">{state === 'sending' ? 'Sending...' : 'Send Message'} <Send size={17} /></button></m.form></div></section> }
